# Generated by Django 5.2.5 on 2025-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField()),
                ('shipping', models.FloatField()),
                ('link', models.URLField(max_length=500)),
                ('in_store', models.BooleanField(verbose_name=False)),
                ('online', models.BooleanField(verbose_name=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
